empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

'''
def DesdeApps(self):
    	    print('======HELLO EVERYBODY======')
'''

app_name="departamento_app"

urlpatterns = [
    path(
        'departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento_list'),
    path('new-departamento/',views.NewDepartamentoView.as_view(),name='nuevo_departamento'),
]

empleado/applications/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="home_app" 

urlpatterns=[
    path(
        'panel/',
        views.HomePage.as_view(),
        name='panel',
    ),

    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    
    path(
        'servicios/',
        views.ServiciosView.as_view(),
        name='servicios'
    ),
    path(
        'equipo/',
        views.EquipoView.as_view(),
        name='equipo'
    ),
    path(
        'contactanos/',
        views.ContactanosView.as_view(),
        name='contactanos'
    ),
    path(
        'ingresar/',
        views.IngresarView.as_view(),
        name='ingresar'
    ),
    path('prueba/',views.PruebaView.as_view()),
    path('lista/',views.PruebaListView.as_view()),
    path('lista-prueba/',views.ListarPrueba.as_view()),
    path('add/',views.PruebaCreateView.as_view(),name='prueba_add'),
    #submétodo as_view: indica que estamos ejecut una vista genérica
    path(
        'resume-foundation/',
        views.ResumeFoundationView.as_view(),
        name='resume_foundation'
    ),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="persona_app"  #para acceder a etiqu name, le doy esta etiqu a todo el conj de urls

urlpatterns=[
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('listar-todo-empleados/',views.ListAllEmpleados.as_view(), name='empleados_all'),
                                                                    #recom acced a través del nombre
    path(
        'lista-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/',views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/',views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'     #nombre para acceder a toda esa url
    ),
    path(
        'update-empleado/<pk>/', #para qu sepa de que registro estoy hablando
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/', #para qu sepa de que registro estoy hablando
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static #ayudara a generar urls estáticas de nuestros archivos multimedia

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.users.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
                                #en base a esta config nos genere una url para la ruta de un 
                                #documento guardado en nuestro documento 

empleado/templates/includes/footerhome.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <title>Document</title>
</head>
    <footer class="text-center">
        <div class="container ">
            <div>
                <div class="row ">
                    <div class="col-md-4 footer-col cuadros ">
                        <h3 class=" ">DIRECCIÓN</h3>
                        <div class="texto ">
                            <h5>La libertad</h5>
                            <h5>Y toda región norte del Perú</h5>
                        </div>
                    </div>
                    <div class="col-md-4 footer-col cuadros ">
                        <h3>REDES SOCIALES</h3>
                        <div class="redes ">
                            <a target="_blank " href="https://www.facebook.com/ServipacPeru" class="btn-social btn-outline texto ">
                                <i class="bi bi-facebook "></i>
                            </a>
                            <a target="_blank " href="https://www.linkedin.com/company/corporacion-servipac-s-a-c" class="btn-social btn-outline texto ">
                                <i class="bi bi-linkedin "></i>
                            </a>
                            <a target="_blank " href="https://www.youtube.com/channel/UC9GACmf8VzBlO3yMtaObWAA" class="btn-social btn-outline texto ">
                                <i class="bi bi-youtube"></i>
                            </a>
                        </div>

                    </div>
                    <div class="col-md-4 footer-col cuadros ">
                        <h3 class=" ">HORARIOS DE ATENCIÓN</h3>
                        <div class="texto ">
                            <h5>Lunes a Domingo</h5>
                            <h5>7am a 10pm</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</html>

empleado/templates/includes/header.html
{% load static %}

<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>

        <div class="top-bar-left">
          <ul class="menu">
            <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
            <li><img src="{% static 'images/logo.png' %}" alt="  " width="100"></li> 
                    <!--redirecciona a añadir empleado-->
          </ul>
        </div>

        <!--
        <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar nuevo</a></li> 
        <li>
          <img src="{% static 'images/logo.png' %}" alt="  " width="100">
        <li class="menu-text"></li><img src="{ %  static 'images/logo.jpg' %}"/></li>  <--comentado estaba
        </li>
        -->
        <li>
          <a href="{% url 'persona_app:empleados_all' %}"><h4>Listar</h4></a>
        </li>

        <li><a href="{% url 'departamento_app:departamento_list' %}"><h4>Departamento</h4></a></li> 
                              <!--error si no declaro nombre a las url de app depart-->
        <li><a href="{% url 'persona_app:empleados_admin' %}"><h4>Administrar</h4></a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}"><h4>Nuevo departamento</h4></a></li>
      </ul>
    </div>


    <div class="top-bar-right">
      <ul class="menu">
        <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
        <li><a href="{% url 'persona_app:empleado_add' %}" class="hollow button"  href="#"><h5>Registrar nuevo</h5></a></li> 
                <!--redirecciona a añadir empleado-->
      </ul>
    </div>

    <div class="top-bar-right">
      <ul class="menu">
        <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
        <li><a href="{% url 'home_app:ingresar' %}" class="hollow button alert" href="#"><h5>Salir</h5></a></li> 
                <!--redirecciona a añadir empleado-->
      </ul>
    </div>
  </div>

empleado/templates/includes/headerhome.html
{% load static %}

<!--
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>

        <div class="top-bar-left">
          <ul class="menu">
          -->
            <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
<!--            <li><img src="{% static 'images/logo.png' %}" alt="  " width="100"></li>  -->
                    <!--redirecciona a añadir empleado-->
<!--          </ul>
        </div>

        <li><a href="{% url 'home_app:inicio' %}"><h4>INICIO</h4></a></li>
        
        <li><a href="{% url 'home_app:servicios' %}"><h4>SERVICIOS</h4></a></li>
        
        <li><a href="{% url 'home_app:equipo' %}"><h4>EQUIPO</h4></a></li>
        
        <li><a href="{% url 'home_app:contactanos' %}"><h4>CONTÁCTANOS</h4></a></li>
        
      </ul>
    </div>
  

    <div class="top-bar-right">
      <ul class="menu"> -->
        <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
<!--        <li><a href="{% url 'home_app:ingresar' %}" class="button"><h5>INGRESAR</h5></a></li> -->
                <!--redirecciona a añadir empleado-->
<!--      </ul>
    </div>
  </div>
-->
<!--
<nav id="menu" class="navbar  sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container-lg">
    <a class="navbar-brand  " href="#">
        <img class="img-fluid rounded float-start" src="{% static 'images/logo.png' %}" alt="" width="80" height="50" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarsExample09">
      <ul class="navbar-nav nav nav-pills">
        
          
          <li class="nav-item ">
              <a class="nav-link" href="{% url 'home_app:inicio' %}">INICIO</a>
          </li>
        
          <li class="nav-item">
              <a class="nav-link" href="{% url 'home_app:servicios' %}">SERVICIOS</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'home_app:equipo' %}">EQUIPO</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'home_app:contactanos' %}">CONTÁCTANOS</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link"  href="{% url 'home_app:ingresar' %}" class="button">INGRESAR</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
-->


<div class="top-bar sticky-top ">
  <div class="top-bar-left">
    
    <ul class="dropdown menu" data-dropdown-menu>

      <div class="top-bar-left">
        <ul class="menu">
          <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
           <li><img src="{% static 'images/logo.png' %}" alt="  " width="100"></li>  
                  <!--redirecciona a añadir empleado-->
        </ul>
      </div>

      <li><a href="{% url 'home_app:inicio' %}">INICIO</a></li>
      
      <li><a href="{% url 'home_app:servicios' %}">SERVICIOS</a></li>
      
      <li><a href="{% url 'home_app:equipo' %}">EQUIPO</a></li>
      
      <li><a href="{% url 'home_app:contactanos' %}">CONTÁCTANOS</a></li>
      
    </ul>
  </div>


  <div class="top-bar-right">
    <ul class="menu">
      <!--<li><input type="search" placeholder="Buscar empleado"></li>-->
      <li><a href="{% url 'home_app:ingresar' %}" class="button"><h5>INGRESAR</h5></a></li> 
              <!--redirecciona a añadir empleado-->
    </ul>
  </div>
</div>