empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="persona_app"  #para acceder a etiqu name, le doy esta etiqu a todo el conj de urls

urlpatterns=[
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('listar-todo-empleados/',views.ListAllEmpleados.as_view(), name='empleados_all'),
                                                                    #recom acced a través del nombre
    path(
        'lista-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/',views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/',views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'     #nombre para acceder a toda esa url
    ),
    path(
        'update-empleado/<pk>/', #para qu sepa de que registro estoy hablando
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/', #para qu sepa de que registro estoy hablando
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static #ayudara a generar urls estáticas de nuestros archivos multimedia

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.users.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
                                #en base a esta config nos genere una url para la ruta de un 
                                #documento guardado en nuestro documento 

empleado/applications/persona/models.py
from django.db import models
#
from applications.departamento.models import departamento 
from applications.users.models import User
#importo tabla.no en departamento,por ello voy a la ruta.
from ckeditor.fields import RichTextField

class Habilidades(models.Model):    #cada empleado va a tener un conjunto de habilidades
    habilidad = models.CharField('Habilidad', max_length=50)    #mc: charfield de habilidades

    class Meta:
        verbose_name='Habilidad'
        verbose_name_plural='Habilidadess Empleados'

    def __str__(self):
        return str(self.id)+'-'+self.habilidad  #retorne algo para que modelo esté commpleto

# Create your models here.
class Empleado(models.Model):
    """Modelo para tabla empleado"""
    JOB_CHOICES=(    #especifico solo valores que puede tener el campo REGISTRO.
        ('0','CONTADOR'),      #en mi BD se guarda la primera columna
        ('1','ADMINISTRADOR'),  #ahorro espacio, pues guardo cadenas de 1 caracter.
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('apellidos', max_length=60)
    full_name = models.CharField(   #concatenar nombre y apellido
        'Nombres completos',
        max_length=120,
        blank=True  #decimos que no es obligatorio
    )               #para ver que esta correcto.hacemos la migración

    job = models.CharField('trabajo', max_length=50,choices=JOB_CHOICES)
    departamento = models.ForeignKey(departamento, on_delete=models.CASCADE) #creamos la relac.
    
    #User = models.ForeignKey(User, on_delete=models.CASCADE) #creamos la 2da relac.

    avatar = models.ImageField(upload_to='empleado', blank=True,null=True) 
                                        #almacena en empleado lo cual lo bussca en carpeta raiz
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida=RichTextField()

    def __str__(self):
        return str(self.id)+'-'+self.first_name+'-'+self.last_name
    

empleado/applications/persona/forms.py
from django import forms
#Como vamos a depender de un modelo creamos un modelform
from .models import Empleado

#Escribo: mf
class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets={
            'habilidades': forms.CheckboxSelectMultiple()

        }

empleado/applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy    #para importar un paquete para redireccion
# Create your views here.
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)

#models
from .models import Empleado
#forms
from .forms import EmpleadoForm
#autentification
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class InicioView(TemplateView):
    """vista que carga la pagina de inicio"""
    template_name='inicio.html'
    
class ListAllEmpleados(ListView):
    template_name='persona/list_all.html'
    paginate_by=4   #tamaño de bloques en que queremos paginar
    ordering='first_name' #ordenar en base al primer nombre
    #model=Empleado
    def get_queryset(self):      #cn esto no será necesario pasarle el parámetro model
        print('***********')
        palabra_clave = self.request.GET.get("kword",'')
        #pedro=pe
        lista=Empleado.objects.filter(
            #first_name=palabra_clave
            first_name__icontains=palabra_clave #busca letra o conj de 2 letras
        )
        return lista

class ListaEmpleadosAdmin(ListView):
    template_name='persona/lista_empleados.html'
    paginate_by=10   #tamaño de bloques en que queremos paginar
    ordering='first_name' #ordenar en base al primer nombre
    context_object_name='empleados'
    model=Empleado
    #Quitamos el query set que servia para hacer filtros



class ListByAreaEmpleado(ListView):
    """lista empleados de una area"""
    template_name='persona/list_by_area.html'
    context_object_name='empleados'
    """queryset=Empleado.objects.filter(
        departamento__shor_name='imp'
    )""" 

    def get_queryset(self): #debe retornar siempre una lista
        #el codigo que quiera
        area=self.kwargs['shorname']
        lista=Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista

class ListEmpleadosByKword(ListView):
    """lista empleados por palabra clave"""
    template_name='persona/by_kword.html'
    context_object_name='empleados'

    def get_queryset(self): 
        print('*********************')
        palabra_clave=self.request.GET.get("kword",'')  #intercepto solicitudes enviadas al servidor
        #print('=====',palabra_clave)                    #en este caso de tipo GET.
        #return []                                       #y q me recupere el valor cuya identif sea keyword
        lista=Empleado.objects.filter(
            first_name=palabra_clave
        )
        #print('lista resultado:', lista)
        return lista
    
class ListHabilidadesEmpleado(ListView):
    """lista empleados de una area"""
    template_name='persona/habilidades.html'
    context_object_name='habilidades'

    def get_queryset(self): #debe retornar siempre una lista
        #el codigo que quiera
        empleado=Empleado.objects.get(id=10) #me recupera 1 reg de la BD
        #print(empleado.habilidades.all()) #voy a reg emplead, al atrib many2many llamad habilid. y met all
        #return []
        return empleado.habilidades.all() #q me muestre a mi template

class EmpleadoDetailView(DetailView):   #para ver detalle de cada empleado
    model=Empleado  #necesita el parametro modelo
    template_name='persona/detail_empleado.html'  #trabaja con un template(vista basada en clase)

    def get_context_data(self, **kwargs): 
        context=super(EmpleadoDetailView,self).get_context_data(**kwargs)
        #Toot un proceso
        context['titulo']='Empleado del mes'
        return context

class SuccessView(TemplateView):            #d35
    template_name="persona/success.html"

class EmpleadoCreateView(CreateView):
    template_name="persona/add.html"
    model=Empleado
    #fields=['first_name','last_name','job']
    #fields=('__all__')  #trae todo los campos del modelo empleado
    form_class=EmpleadoForm     #configurar y personalizar lso formularios
    '''
    fields=[
        'first_name',   #especificamos solo los atributos queremos se visualien
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar',
    ]
    '''
    #success_url='.'   #<--si quiero que recargue la misma pagina
    #success_url='/success'          #d35
    success_url=reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form): #almacena el formulario que estamos enviando dsd registrar persona.
        #logica del proceso
        empleado=form.save(commit=False)    #guardar lo que estoy llenando (no es muy optimo)
        empleado.full_name=empleado.first_name+' '+empleado.last_name
        empleado.save()     #para que full_name se refleje en BD
        return super(EmpleadoCreateView,self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    fields=[
        'first_name',  #campos que deseo modificar
        'last_name',
        'job',
        'departamento',
        'habilidades'
    ]
    success_url=reverse_lazy('persona_app:empleados_admin') 
    #nose redirecciona cuando el proceso es completo, le digo que no se vaya a url correcto, sino
    #a empleados_admin que ees la vista desde donde modificamos

    def post(self, request, *args, **kwargs):  #post se ejecutará 1º
        self.object = self.get_object()
        print('**************METODO POST*************')
        print('**************************************')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):                 #y luego resien este form_valid
        #logica del proceso
        self.object = self.get_object()
        print('**************METODO form valid*************')
        print('**************************************')
        return super(EmpleadoUpdateView,self).form_valid(form)

class EmpleadoDeleteView(DeleteView):
    model=Empleado
    template_name="persona/delete.html"
    success_url=reverse_lazy("persona_app:empleados_admin")

'''
def login_request(request):
    form=AuthenticationForm()
    return render(request,"")
'''

empleado/templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
    Registrar Empleado
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %} 
                                        <!--IMPORTANTE!!! añadir: enctype="multipart/form-data": indica a 
                                        html que debe aceptar archivos que tengan otro tipo de extensión-->
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>foto:
                    {{form.avatar}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>

        </form>
    </div>
</div>

<!--
<input type="text" placeholder="nombres">
<input type="text" placeholder="apellidos">  
-->
<!--
{{form.as_p}}   
-->
<!--
<form method="POST">{% csrf_token %}   token de seguridad para q el servidor acepte la petición
    {{form.as_p}}
    <button type="Submit">Agregar</button>     boton que hace ejecución del metodo
</form>
-->
{% endblock content %}

empleado/templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}  <!--aa traves de este token la comunicación es segura-->
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aquí">
    <button type="submit">Buscar</button>   <!--boton q ejecutará el metod.submit para activ el metod GET-->
</form>

<h3>Lista resultados</h3>

<ul>
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
</ul>

empleado/templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{ object.first_name }}</h1> <!--Le decimos que sea hijo de foundation-->

        <form class ="cell" method="POST">{% csrf_token %} <!--Tmb con cell indicamos que es hijo del grid-x-->
            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
            <!--
            <p>Confirme que desea eliminar</p>
            <button type="submit">Confirmar</button> 
            -->
            
        </form>
    </div>
</div>

{% endblock content %}
    

empleado/templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}  <!--siempre que usemos static debemos importar este-->

{% block title %}
    {{ object.first_name }}
{% endblock title %}


{% block content %}
{% include "includes/header.html" %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
                {{ empleado.get_job_display }}      <!--empleado es un modelo que se manda como objeto a este template-->
                                    <!--que nos recupere el sig valor de su diccionario-->
            </div>

            <!--creamos validacion para que muestre una img cuando exista y otra cuando no-->
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}"> <!--para accder a una variable de DJ dentro del template: los parent-->
            {% else %}
                <img src="{% static 'images/mantenimiento_camiones_2.jpg' %}">  
            {% endif %}
        
            <div class="card-section">
                <h4>{{ empleado.first_name }}</h4>
                <p>{{ empleado.last_name }}</p>
                <p>{{ empleado.departamento.name }}</p>
                <p><span class="label">Habilidades:</span></p>
                <ul class="vertical menu">
                    
                    {% for h in empleado.habilidades.all %}
                        <li> {{h.habilidad}} </li>
                    {% endfor %}
                        
                </ul>
                <!--<p>{{ empleado.habilidades }}</p>-->
            </div>
        </div>
    </div>
</div>
{% endblock content %}
 <!--
<h1>Detalle de un empleado {{titulo}}</h1>

{{empleado}}

<h3>Todos los datos:</h3>
<p>{{empleado.first_name}}</p>   accedo a cada uno de los atributos del modelo  
<p>{{empleado.last_name}}</p>
<p>{{empleado.departamento}}</p>
<p>{{empleado.habilidades}}</p>
-->

empleado/templates/persona/habilidades.html
<h1>Habilidades de empleados</h1>

<ul>
    {% for h in habilidades %}
        <li>{{h}}</li>
    {% endfor %}
</ul>

empleado/templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<!--{{object_list}}-->

<div class="grid-container">
    <!--dentro construimos los 3 bloques-->
    <div class="grid-x">
        <h1 class="cell">Lista empleados</h1>

        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}<!--separación. Token autent-->
            <div class="cell large-7">
                <!--aqui va la caja de texto-->
                <input type="text" id="kword" name="kword" placeholder="buscar empleado"> <!--id,name recuperamos-->
            </div>
            <div class="cell large-2">
                <!--Aqui va botón buscar-->
                <button type="submit" class="success button">Buscar</button>    <!--en vez de get, submit-->
            </div>
        </form>

        <div class="cell">
            <!--Aqui va las tablas-->
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCIÓN</th>
                  </tr>
                </thead>
                <tbody>
                    <!--elementos que se cargan en la lista-->
                    {% for e in object_list %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <!--<td><a class="button warning" href="#">ver</a></td>   -> Acción ver-->
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">ver</a></td>
                    </tr> 
                    {% endfor %}
                </tbody>
              </table>
        </div>

        <!--Para paginación-->
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                    </li>                      
                    {% endif %}
                    <!--
                    {% for pagina in paginator.page_range %}
                    <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endfor %}
                    -->

                    <!--resaltar página-->
                    {% for pagina in paginator.page_range %}
                    {%ifequal pagina page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                    {% endifequal %}
                    {% endfor %}
                    
                    <!--valdiamos que exista la pag de atrás y siguiente-->
                    {%if page_obj.has_next %}   
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li> 
                    {% endif %}    
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>

    <!--<h1>Lista de todos los empleados</h1>-->
    <!--
    <ul>
        {%for e in object_list %}
            <li>{{e}}</li>
        {%endfor %}
    </ul>
    -->
</div>

{% endblock content %}

empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    lista empleados por departamento
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area</div>
            <div class="cell">
                <!--ponemos la tabla ya hecha en list_all.html-->
                <!--Tablas-->
                <table>
                    <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCIÓN</th>
                    </tr>
                    </thead>
                    <tbody>
                        <!--elementos que se cargan en la lista-->
                        {% for e in object_list %}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <!--<td><a class="button warning" href="#">ver</a></td>   -> Acción ver-->
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">ver</a></td>
                        </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

    
<h1>Lista empleados por departamento</h1>

<!--{{object_list}}-->
<ul>
    {% for e in object_list %}
        <li>{{e}}</li>
    {% endfor %}
</ul>

empleado/templates/persona/lista_empleados.html
<!--Inicialmente copiamos todo de list_all, porque es similar-->
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<!--{{object_list}}-->

<div class="grid-container">
    <!--dentro construimos los 3 bloques-->
    <div class="grid-x">
        <h1 class="cell">Lista empleados</h1>
        <!--El form ha sido borrado porque no hay formulario-->

        <div class="cell">
            <!--Aqui va las tablas-->
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCIÓN</th>
                  </tr>
                </thead>
                <tbody>
                    <!--elementos que se cargan en la lista-->
                    {% for e in object_list %}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <!--<td><a class="button warning" href="#">ver</a></td>   -> Acción ver-->
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a> 
                                                             <!--el id xq necesitamos saber que emmleado editar (pk)-->
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr> 
                    {% endfor %}
                </tbody>
              </table>
        </div>

        <!--Para paginación-->
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                    </li>                      
                    {% endif %}
                    <!--
                    {% for pagina in paginator.page_range %}
                    <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endfor %}
                    -->

                    <!--resaltar página-->
                    {% for pagina in paginator.page_range %}
                    {%ifequal pagina page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                    {% endifequal %}
                    {% endfor %}
                    
                    <!--valdiamos que exista la pag de atrás y siguiente-->
                    {%if page_obj.has_next %}   
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li> 
                    {% endif %}    
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>

    <!--<h1>Lista de todos los empleados</h1>-->
    <!--
    <ul>
        {%for e in object_list %}
            <li>{{e}}</li>
        {%endfor %}
    </ul>
    -->
</div>

{% endblock content %}

empleado/templates/persona/success.html
<h1>¡Felicitaciones!, se guardó correctamente el empleado</h1>

empleado/templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
    Editar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <!--{{form.as_p}}-->       <!--as_p: para que me muestre hacia abajo-->
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}   <!--token de seguridad para q el servidor acepte la petición-->
                        <!--grid-margin-x: para separar-->
                <div class="cell large-6">  <!--large: para que en pantalla grande se divida en 6-->
                    <label>Nombres:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell large-6">     <!--Nota: Ctrl+z para identar corectamente -->
                    <label>Apellidos:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">  
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">  
                    <label>Area:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">     
                    <label>Habilidades extra:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">  <!--cell: para que ocupe todo-->  
                    <button type="submit" class="success button">Guardar</button> <!--boton ejecuta metodo-->
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}