empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

'''
def DesdeApps(self):
    	    print('======HELLO EVERYBODY======')
'''

app_name="departamento_app"

urlpatterns = [
    path(
        'departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento_list'),
    path('new-departamento/',views.NewDepartamentoView.as_view(),name='nuevo_departamento'),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="persona_app"  #para acceder a etiqu name, le doy esta etiqu a todo el conj de urls

urlpatterns=[
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('listar-todo-empleados/',views.ListAllEmpleados.as_view(), name='empleados_all'),
                                                                    #recom acced a través del nombre
    path(
        'lista-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/',views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/',views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'     #nombre para acceder a toda esa url
    ),
    path(
        'update-empleado/<pk>/', #para qu sepa de que registro estoy hablando
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/', #para qu sepa de que registro estoy hablando
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static #ayudara a generar urls estáticas de nuestros archivos multimedia

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.users.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
                                #en base a esta config nos genere una url para la ruta de un 
                                #documento guardado en nuestro documento 

empleado/applications/departamento/models.py
from django.db import models
# Create your models here.
class departamento (models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True)  #especificamos cantidad razonable
    shor_name=models.CharField('Nombre Corto',max_length=20) #CharField: usaremos la ORM de DJ
    anulate = models.BooleanField('Anulado',default=False) #si no especificamos,el valor del anulate,DJ le pondrá FALSO.

    class Meta:
        verbose_name='Mi departamento'  #Nombre de nuestro modelo
        verbose_name_plural='Areas de la empresa'   #Nombre que indic. a DJ que tenga cuando quiera mostrarlo en plural
        ordering=['-name']  #ordenar departamentos listado: name:orden alfab. -name: orden inverso
        unique_together=('name','shor_name') #no permite que se registre un atributo 2 veces o combinación de ellas.

        #TAREA: HACER LO MISMO PARA APP PERSONA.

    def __str__(self):
        return str(self.id)+'-'+self.name+'-'+self.shor_name

empleado/applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre=forms.CharField(max_length=50)
    apellidos=forms.CharField(max_length=50)
    departamento=forms.CharField(max_length=50)
    shorname=forms.CharField(max_length=20)
    

empleado/applications/departamento/views.py
from django.shortcuts import render

from django.views.generic import ListView
from django.views.generic.edit import FormView
from applications.persona.models import Empleado    #si esta en otra app
from .models import departamento
# Create your views here.
from .forms import NewDepartamentoForm      # . si está a la misma altura


class DepartamentoListView(ListView):
    template_name='departamento/lista.html'
    model=departamento  #formulario para que reciba datos
    context_object_name='departamentos' #lo redefinimos para usar el nombre'depart..'  en html.

#class NewDepartamentoView(FormView):
class NewDepartamentoView(FormView):
    
    template_name='departamento/new_departamento.html'
    form_class=NewDepartamentoForm  #formulario para que reciba datos
    success_url='/'

    def form_valid(self,form):
        print('*******estamos en el form  valid****')
        
        depa=departamento(          #instancia del modelo departamento
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()     #para guardar en la BD
        
        nombre=form.cleaned_data['nombre']
        apellido=form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        
        return super(NewDepartamentoView,self).form_valid(form)

empleado/templates/departamento/lista.html
{% extends 'base.html' %}  <!--decimos  que herede de base.html-->


{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">    <!--para que este centrado y con márgenes-->
        <div class="grid-x">    <!--definimos grid para las columnas-->
            <h1 class="cell">Lista departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>     <!--cuerpo de la tabla-->
                        
                        {% for departamento in departamentos %} <!--listamos departamento-->
                        <tr>
                            <td>{{ departamento.name }}</td>   <!--para las celdas-->
                            <td>{{ departamento.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    Registrar Departamento
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}    
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>apellidos:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>departamento:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>shorname:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
<!--
<h1>Registrar nuevo departamento</h1>

<form method="POST"> {% csrf_token %}
    #{{form.as_p}}
    
    <h3>Datos empleado</h3>
    <p>
        {{form.nombre}}
    </p>
    <p>
        {{form.apellidos}}
    </p>
    <h3>Datos de departamento</h3>
    <p>
        {{form.departamento}}
    </p>
    <p>
        {{form.shorname}}
    </p>

    <button type="submit">Guardar</button>
</form>
-->