empleado/applications/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="home_app" 

urlpatterns=[
    path(
        'panel/',
        views.HomePage.as_view(),
        name='panel',
    ),

    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    
    path(
        'servicios/',
        views.ServiciosView.as_view(),
        name='servicios'
    ),
    path(
        'equipo/',
        views.EquipoView.as_view(),
        name='equipo'
    ),
    path(
        'contactanos/',
        views.ContactanosView.as_view(),
        name='contactanos'
    ),
    path(
        'ingresar/',
        views.IngresarView.as_view(),
        name='ingresar'
    ),
    path('prueba/',views.PruebaView.as_view()),
    path('lista/',views.PruebaListView.as_view()),
    path('lista-prueba/',views.ListarPrueba.as_view()),
    path('add/',views.PruebaCreateView.as_view(),name='prueba_add'),
    #submétodo as_view: indica que estamos ejecut una vista genérica
    path(
        'resume-foundation/',
        views.ResumeFoundationView.as_view(),
        name='resume_foundation'
    ),
]

empleado/applications/users/urls.py
from django.urls import path
from . import views

app_name="users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static #ayudara a generar urls estáticas de nuestros archivos multimedia

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.users.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
                                #en base a esta config nos genere una url para la ruta de un 
                                #documento guardado en nuestro documento 

empleado/applications/home/models.py
from django.db import models

# Create your models here.
class Prueba(models.Model):
    titulo = models.CharField(max_length=100)
    subtitulo = models.CharField(max_length=50)
    cantidad = models.IntegerField()

    def __str__(self):  #me ofrece retornar una variable
        return self.titulo+' - '+self.subtitulo

empleado/applications/home/forms.py
#Acá escribiré las personalizaciones para los campos
from django import forms #paquete interno que me ayuda a crear formularios
from .models import Prueba

class PruebaForm(forms.ModelForm):
    class Meta:
        model=Prueba
        #fields=('__all__')
        fields=(
            'titulo',
            'subtitulo',
            'cantidad',
        )
        widgets={
            'titulo':forms.TextInput(
                attrs={
                    'placeholder':'Ingrese texto aquí'
                }
            )
        }
    '''
    def clean_cantidad(self):  #a la altura de class xq estamos escrib un metodo para prueba form
        cantidad = self.cleaned_data['cantidad'] #recupero lo que se escribe en cantidad
        if cantidad<10:
            raise forms.ValidationError('Ingrese un numero mayor a 10')

        return cantidad
    '''

empleado/applications/home/views.py
from django.shortcuts import render

# Create your views here.
#from django.views.generic import TemplateView, ListView, CreateView
from django.views.generic import (
    TemplateView, 
    ListView, 
    CreateView
)
# Import models
from .models import Prueba 
from .forms import PruebaForm  #para el model form parte1


class HomePage(TemplateView): #agregado
    template_name='home/index.html'

class InicioView(TemplateView):
    template_name='iniciohome.html'
'''
class NosotrosView(TemplateView):
    template_name='home/nosotroshome.html'
'''
class ServiciosView(TemplateView):
    template_name='home/servicioshome.html'

class EquipoView(TemplateView):
    template_name='home/equipohome.html'

class ContactanosView(TemplateView):
    template_name='home/contactanoshome.html'

class IngresarView(TemplateView):
    template_name='home/ingresarhome.html'

class PruebaView(TemplateView):
    template_name='home/prueba.html'

class ResumeFoundationView(TemplateView):
    template_name='home/resume_foundation.html'


class PruebaListView(ListView):     #PruebaListVies es una lista genérica
    template_name = 'home/lista.html'
    context_object_name='listaNumeros'
    queryset=['5','10','15']     #no solo pueden ser así, sino registros de una BD.


class ListarPrueba(ListView):   #El listview heredo de la vista genérica. 
                                #interpreta que quiero listar todo o que tenga el modelo prueba. 
    template_name = "home/lista_prueba.html"  #ubicación
    model=Prueba
    context_object_name='lista'  #accedemos al resultado de listar de tabla prueba.


class PruebaCreateView(CreateView):         #formulario
    template_name = "home/add.html"
    model=Prueba
    #fields=['titulo','subtitulo','cantidad']
    form_class=PruebaForm
    success_url='/' #Al copletarse el proceso va a la pagina principal o de inicio 

    

empleado/templates/home/add.html
<h2>Prueba de createview</h2>
<!--<input type="text" placeholder="Ingrese titulo">-->
<form method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">Guardar</button>
</form>

<!--
<label for="prueba">prueba:</label>
<input type="text" placeholder="Ingrese texto aquí">
-->

empleado/templates/home/contactanoshome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
<link rel="stylesheet" href="{% static 'css/responsive.css' %}" />



<section class=" " id="contactanos_container">
    <div class="row align-items-center caja_contacto ">
        <h2 id="contactanos" class="titulo ">¡Regístrate, y te regalamos 1 consulta gratuita con un especialista!</h2>
        <div class="caja__contacto">
            <div class="contactar col-4 col-md-6 col-sm-12 ">
                <form>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlInput1 ">NOMBRE y APELLIDO</label>
                        <input type="text " class="form-control " onkeypress="return letra(event)" placeholder="NOMBRE y APELLIDO " required>
                    </div>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlInput1 ">CORREO</label>
                        <input type="email " class="form-control " id="exampleFormControlInput1 " placeholder="CORREO " required>
                    </div>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlInput1 ">
                        TELEFONO
                    </label>
                        <input type="text " class="form-control " onkeypress="return numeros(event)" placeholder="NUMERO DE TELEFONO " required>
                    </div>
                    <div class="form-group espaci ">
                        <label for="exampleFormControlTextarea1 ">
                        MENSAJE O CONSULTA
                    </label>
                        <textarea class="form-control " id="exampleFormControlTextarea1 " rows="3 " required>
                    </textarea>
                    </div>
                    <button type="submit " class="btn btn-primary col-lg-12 col-xl-2 mt-2">REGISTRAR</button>

                </form>
            </div>
            <div class=" col-4 col-md-6 col-sm-12 caja-mapa">
                <div class="mapa ">
                    <a href="https://goo.gl/maps/GQybnVEtwnMT8EH56 ">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d16135231.61288914!2d-84.06739743910542!3d-9.130472692183531!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c850c05914f5%3A0xf29e011279210648!2zUGVyw7o!5e0!3m2!1ses!2spe!4v1620188007667!5m2!1ses!2spe" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                            
                            
                    </a>
                </div>

                <div class="location-container container-sm border row align-items-center ">
                    <div class=" col-3 ">
                        <div class="location ">
                            <div class="location-icon ">
                                <i class="bi bi-cursor-fill "></i>
                            </div>
                        </div>
                    </div>
                    <div class="col ">
                        <p class="my-1 ">Ubicacion</p>
                        <p class="my-1 ">La libertad y toda región norte del Perú</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'includes/footerhome.html' %}

{% endblock content %}

empleado/templates/home/equipohome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/equipo.css' %}" >
    <title></title>
</head>

<body>
    <div class="equipo">
        <div class="texto">
            <h1>nuestro equipo</h1>
            <p> Nuestro Equipo Sabemos lo que hacemos, sabemos lo que tus unidades se merece</p>
        </div>
        <div class="imagenes">
            <div class="trabajadores">
                <img src="{% static 'images/Jose_Pacheco-Jefe_de_logística.jpg' %}" alt="">
                <div class="descripcion">
                    <h2>Jose Pacheco</h2>
                    <p>
                        Jefe de logística
                    </p>
                </div>
            </div>
            <div class="trabajadores">
                <img src="{% static 'images/Brayan_Alan-Técnico_de_mantenimiento.jpg' %}" alt="">
                <div class="descripcion">
                    <h2>Fernando Romero</h2>
                    <p>
                        Ingeniero Supervisor
                    </p>
                </div>
            </div>
            <div class="trabajadores">
                <img src="{% static 'images/Fernando_Romero-Ingeniero_Supervisor.jpg' %}"  alt="">
                <div class="descripcion">
                    <h2>Brayan Alan</h2>
                    <p>
                        Técnico de mantenimiento
                    </p>
                </div>
            </div>
            <div class="trabajadores">
                <img src="{% static 'images/Ronald_Rivera-Asesor_de_Servicio.jpg' %}" alt="">
                <div class="descripcion">
                    <h2>Ronald Rivera</h2>
                    <p>
                        Asesor de Servicio
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

{% include 'includes/footerhome.html' %}

{% endblock content %}

empleado/templates/home/home2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>Titutlo de la pagina</title>
</head>

<header style="border:solid red;height: 40px;">
    <a href="">opcion uno</a>
    <a href="">opcion dos</a>
    <a href="">opcion tres</a>
</header>

<body>
    <h1>Resumen Foundation</h1>
    <div class="grid-x" style="border: 1px solid green;">
        <h2 class="cell small-12 large-5" style="border: 1px solid red;">elemento 1</h2>
        <h2 class="cell large-4">elemento 2</h2>
        <h2 class="cell large-3" style="border: 1px solid red;">elemento 3</h2>
        <div class="cell large-4 grid-x" style="border: 1px solid yellow;">
            <h4 class="cell large-2">otro elemento 1</h4>
            <h4 class="cell large-2">otro elemento 2</h4>
            <h4>otro elemento 3</h4>
        </div>
    </div>
</body>
</html>

empleado/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de usuario</h1>
    <h3>Bienvenido: {{user}}</h3>
    <ul>
        <li><a href="{% url 'users_app:user-logout' %}">Cerrar sesion</a></li>
        <li><a href="#">Actualizar datos</a></li>
    </ul>
</body>
</html>

empleado/templates/home/ingresarhome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script
      src="https://kit.fontawesome.com/64d58efce2.js"
    ></script>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <title>LOGIN SERVIPAC</title>
  </head>
  <body>
    <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
          <form action="#" class="sign-in-form">
            <h2 class="title">INGRESAR</h2>
            

            <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
              <div class="grid-container">
                <div class="grid-x grid-padding-x">
                  
                  <div class="medium-12 cell">
                    <label>Usuario
                      <input type="text" placeholder="USUARIO">
                    </label>
                    <label>contraseña
                      <input type="text" placeholder="CONTRASEÑA">
                    </label>
                    
                    <button type="submit" class="button">INGRESAR</button>
                  </div>
                  
                </div>
                <p class="social-text">INGRESAR CON OTRA PLATAFORMA</p>
              </div>
            </form>

            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
        </div>
      </div>

      <div class="panels-container">
        <div class="panel left-panel">
          <div class="content">
            <h3>¿Alguna duda?</h3>
            <p>
              Comunicate con soporte técnico servipacsoporte@servipac.com.pe
            </p>
            <i class="fas fa-envelope"></i>
          </div>
          <img src="{% static 'images/log.svg' %}" alt="">
          
        </div>
      </div>
      
    </div>

    <script src="{% static 'js/app.js' %}"></script>
  </body>

</html>

{% endblock content %}

empleado/templates/home/iniciohome.html
{% extends 'basehome.html' %}

empleado/templates/home/lista.html
<h1>Prueba de ListView</h1>

{{listaNumeros}}

empleado/templates/home/lista_prueba.html
<h1>Lista prueba listview</h1>


{% for elemento in lista %} <!--elemento: lo que quiero iterar
                            lista: en el que quiero iterar ese elem.-->
    <p>
        {{elemento.cantidad}}-{{elemento.titulo}}  <!--cantidad. titulo.-->
    </p>
{% endfor %}
    
<!--{{lista}}-->

empleado/templates/home/nosotroshome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}

<h1>soy la parte nosotros</h1>
{% endblock content %}

empleado/templates/home/prueba.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!--<link rel="stylesheet" href="{% static 'css/prueba.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
</head>
<body>
    <h1 class="ejemplo1">Hola mundo desde los nuevos templates</h1>
    <h2 class="ejemplo2">Cargando estilos</h2>
    
    <!-- Anchors (links) -->
    <a href="about.html" class="button">Learn More</a>
    <a href="#features" class="button">View All Features</a>

    <!-- Buttons (actions) -->
    <button type="button" class="success button">Save</button>
    <button type="button" class="alert button">Delete</button>
    
</body>
</html>

empleado/templates/home/resume_foundation.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>Resumen Foundation</h1>
    <div class="grid-x" style="border: 1px solid green;">
        <h2 class="cell small-12 large-5" style="border: 1px solid red;">elemento 1</h2>
        <h2 class="cell large-4">elemento 2</h2>
        <h2 class="cell large-3" style="border: 1px solid red;">elemento 3</h2>
        <div class="cell large-4 grid-x" style="border: 1px solid yellow;">
            <h4 class="cell large-2">otro elemento 1</h4>
            <h4 class="cell large-2">otro elemento 2</h4>
            <h4>otro elemento 3</h4>
        </div>
    </div>
</body>
</html>

empleado/templates/home/servicioshome.html
{% extends 'basehome.html' %}

{% block title %} Pagina de inicio SERVIPAC{% endblock title %}


{% block content %}

{% include 'includes/headerhome.html' %}
{% load static %}
  


  <link rel="stylesheet" href="{% static 'css/estilos2.css' %}" />
 
    <div class="servicios">
      <div class="servicios__items">
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/Diagnostico_Y_Reparación_Del_Sistema.jpg' %}"  alt="" />
        
          </div>
          <div class="items_textos">
            <h2>Diagnostico Y Reparación Del Sistema</h2>
            <p>
                Solucionamos todo el sistema eléctrico de tu 
                unidad, te atendemos en tu propia empresa.
            </p>
          </div>
        </div>
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/Luces_Filtros_Frenos_Y_Bateria.jpg' %}"  alt="" />
          </div>
          <div class="items_textos">
            <h2>Luces Filtros Frenos Y Bateria</h2>
            <p>
                De todo para que este al 100% operativa en todo momento.
            </p>
          </div>
        </div>
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/mantenimiento_de_vehículos.jpg' %}"  alt="" />
             
          </div>
          <div class="items_textos">
            <h2>mantenimiento de vehículos</h2>
            <p>
                Tus unidades merecen tener la mejor vida útil y 
                tus neumáticos también, te damos el mantenimiento 
                gratis.
            </p>
          </div>
        </div>
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/Neumáticos_Y_Balanceo_De_Ruedas.jpg' %}"  alt="" />
          </div>
          <div class="items_textos">
            <h2>Neumáticos Y Balanceo De Ruedas</h2>
            <p>
                Equilibramos el peso de tus ruedas, de modo que garantizamos 
                que las llantas de su vehículo giren sin vibrar
            </p>
          </div>
        </div>
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/sistema_hidráulico.jpg' %}" alt="" />
        
          </div>
          <div class="items_textos">
            <h2>sistema hidráulico</h2>
            <p>
                Te ayudamos a que funcione y realizar 
                tus operaciones logísticas.
            </p>
          </div>
        </div>
        <div class="items">
          <div class="items_img">
            <img src="{% static 'images/transporte_y_distribucion.jpg' %}"alt="" />
          </div>
          <div class="items_textos">
            <h2>transporte y distribucion</h2>
            <p>
                Sabemos que tu mercancía no se puede detener, 
                Por eso te brindamos el servicio de auxilio 
                mecánicos las 24 horas.
            </p>
          </div>
        </div>
      </div>
    </div>




<!--Inicio de la imagen de portada-->
<!--eliminado-->
<!--Fin de la imagen de portada-->

{% include 'includes/footerhome.html' %}

{% endblock content %}